
services:
    web:
        image: rois2coeurs/url-shortening-srv:latest
        volumes:
          - data:/usr/src/app/data
        networks:
          - nginx

volumes:
    data:

networks:
    nginx:
        external: true